from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(summary):
    file_name = "AutoInsights_Report.pdf"

    doc = SimpleDocTemplate(file_name, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("AutoInsights Project Report", styles['Title']))
    story.append(Spacer(1, 20))

    story.append(Paragraph("Executive Summary", styles['Heading1']))

    for item in summary:
        story.append(Paragraph(str(item), styles['Normal']))
        story.append(Spacer(1, 10))

    story.append(Spacer(1, 20))
    story.append(Paragraph("System Features", styles['Heading1']))

    features = [
        "Automated data cleaning",
        "Advanced churn prediction models",
        "Interactive EDA dashboard",
        "Model comparison analytics",
        "Dynamic prediction engine",
        "Business insight generation"
    ]

    story.append(
        ListFlowable([
            ListItem(Paragraph(f, styles['Normal'])) for f in features
        ])
    )

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by AutoInsights Platform", styles['Italic']))

    doc.build(story)

    return file_name